### ISSUE TITLE
Reworking deployment

### ISSUE THREAD

**Issue by bilgorajskim** [Jordan141/articleblog#272]
The idea is:

- build app image inside CI
- save built image to a file
- send this file to the server
- load file into docker on the server
- stop existing app container (if it is running) and delete its image
- start new app container with fresh image

All of this would be executed by CI.

The main benefit is the reduction of downtime during deployment. Currently the image is built on the server, and the container is shut down during the build. With the above solution, the downtime is reduced to the time needed to stop and start a container. (with some more work it's possible to have 0 downtime deployment by configuring Nginx to listen to 2 localhost servers on different ports. the new container would be started first, then once it is up the old container would be stopped; both will operate on different ports and nginx will be able to pass traffic in a way that ensures no downtime).

Another benefit is that the server no longer has to keep an up to date repository. It doesn't really need to keep the repository at all. It just runs images. The app can be deployed on a freshy spinned up server that has only docker installed and .env file placed somewhere.

In this setup, docker-compose would be used only for local development. The CI won't use docker-compose, neither will the server use it.

The downside is that the action will take longer to process, because the building process will happen inside it. And the workflow file will grow in size quite a bit.

Below is a workflow that I use in another app that does what is described here. Although there is a difference in that it stops the container and deletes old image before loading new one - this is done because of very limited disk space. 

```yaml
steps:
    - uses: actions/checkout@v2
    with:
        fetch-depth: 100

    - name: Build Docker image
    env:
        IMAGE_TAG: ${{ github.sha }}
    run: |
        docker build -f app/Dockerfile -t "app:$IMAGE_TAG" .
        docker save "app:$IMAGE_TAG" -o app.img
    
    - name: Send Docker image
    env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        APP_HOST: ${{ secrets.APP_HOST }}
        APP_USERNAME: ${{ secrets.APP_USERNAME }}
        APP_TMP_DIR: ${{ secrets.APP_TMP_DIR }}
    run: |
        mkdir ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/gh_actions_key
        chmod 600 ~/.ssh/gh_actions_key
        echo "$APP_USERNAME@$APP_HOST:22:$APP_TMP_DIR"
        rsync -avz -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" ./app.img "$APP_USERNAME@$APP_HOST:$APP_TMP_DIR"
    
    - name: Load Docker image and start service
    uses: appleboy/ssh-action@master
    env:
        APP_TMP_DIR: ${{ secrets.APP_TMP_DIR }}
        IMAGE_TAG: ${{ github.sha }}
    with:
        host: ${{ secrets.APP_HOST }}
        port: 22
        username: ${{ secrets.APP_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        envs: APP_TMP_DIR,IMAGE_TAG
        script: |
        sudo docker stop app || true;
        sudo docker rm app || true;
        sudo docker load < "$APP_TMP_DIR/app.img";
        rm "$APP_TMP_DIR/app.img" || true;
        sudo docker run --name app --restart always --net host -d \
        --env-file /home/ubuntu/.env -v /home/ubuntu/.env:/application/app/.env.local \
        -v /home/ubuntu/firebase-key.json:/application/app/firebase-key.json \
        -v /home/ubuntu/app/data:/application/app/data \
        -v /home/ubuntu/app/feeds:/application/app/feeds "app:$IMAGE_TAG";
        sudo docker image prune --all --force
```
